### ISSUE TITLE
Unable to spinup workspace in gitpod selfhosting

### ISSUE THREAD

**Issue by chaitu454** [gitpod-io/spring-petclinic#45]
Below is the error I am getting while trying to spin up workspace on self hosted gitpod version 0.9.0-alpha1.

Can anyone please suggest.

cannot prepare for user namespaces: rpc error: code = Internal desc = cannot find workspace container

**Comment by fntlnz** [comment]
Discussion is taking place at https://community.gitpod.io/t/issue-with-gitpod-self-hosting-0-9-0-alpha1/3656
